# This file configures `borg` with patterns fit for any Cybersecurity Development repository

# This is the default configuration used by `borg` if no other configuration is given
# Borg config can be overridden either by an alternate local or remote .borg.toml

# This file is hosted at 
# https://raw.githubusercontent.com/techservicesillinois/template_repo_sync/refs/heads/main/default.borg.toml

[template]
files_url = "https://raw.githubusercontent.com/techservicesillinois/secdev-template-python/refs/heads/main/"
files = [
    ".github/workflows/pr_reminder.yml",
    ".github/workflows/cleanup.yml",
    "CODE_OF_CONDUCT.md",
    "SECURITY.md",
]
[generate.gitattributes]
# Include all template files above
include_template_files = true
